name: 'Luna ML action'
description: 'Sync projects and models from the repository'
inputs:
  server:  # id of input
    description: 'Luna ML server URL (e.g. https://some.domain.com)'
    required: false
    default: 'https://luna.staroid.com'
  version:
    description: 'Luna ML Client version to use'
    required: false
    default: ''
  access-token:
    description: 'Github access token'
    required: false
    default: ''
  localeval:
    description: 'Evaluate locally'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Install Latest Luna ML package
      shell: bash
      run: |
        if [ "${{ inputs.version }}" == "" ]; then
          pip install luna-ml
        else
          pip install luna-ml==${{ inputs.version }}
        fi
    - name: Sync
      shell: bash
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          echo "git fetch origin $GITHUB_BASE_REF"
          git fetch origin $GITHUB_BASE_REF

          # sync with local server
          ORIG_COMMIT="origin/$GITHUB_BASE_REF"
          CURRENT_COMMIT="HEAD"

          # print task pod logs
          curl -s -L -O https://github.com/wercker/stern/releases/download/1.11.0/stern_linux_amd64
          chmod +x stern_linux_amd64
          ./stern_linux_amd64 -n default '.*' &

          echo "Evaluate locally"
          luna-ml --server ${{ inputs.server }} sync \
            --orig_commit "$ORIG_COMMIT" \
            --current_commit "$CURRENT_COMMIT" \
            --dry-run false \
            --eval local \
            --wait true .
        elif [ "${{ github.event_name }}" == "push" ]; then
          set +e
          git show -s ${{ github.event.before }}
          if [ $? -ne 0 ]; then
            echo ""
            echo "+------------------------------------------------------------+"
            echo "| Maybe, the branch is deleted after the Pull request merge, |"
            echo "| or pushed directly without making Pull request?            |"
            echo "| Please keep the branch until this action finishes.         |"
            echo "+------------------------------------------------------------+"
            echo ""
            exit -1
          fi
          set -e

          ORIG_COMMIT=${{ github.event.before }}
          CURRENT_COMMIT="HEAD"
          echo "Update remote server ${{ inputs.server }}"
          luna-ml --server ${{ inputs.server }} sync \
            --orig_commit "$ORIG_COMMIT" \
            --current_commit "$CURRENT_COMMIT" \
            --dry-run false \
            --eval true \
            --wait false .
        else
          echo "Event ${{ github.event_name }} is not supported"
          exit 1
        fi
      env:
        REPO_TYPE: github.com
        REPO_NAME: ${{ github.repository }}
        LUNA_ACCESS_TOKEN: ${{ inputs.access-token }}
