name: 'Luna ML action'
description: 'Sync projects and models from the repository'
inputs:
  server:  # id of input
    description: 'Luna ML server URL (e.g. https://some.domain.com'
    required: true
    default: 'http://localhost:5000'
  version:
    description: 'Luna ML version to use'
    required: true
    default: 'main'
  github-token:
    description: 'Github Token'
    required: false
    default: ''
  localeval:
    description: 'Evaluate locally'
    required: false
    default: 'false'    
runs:
  using: "composite"
  steps:
    - name: Install Latest Luna ML package
      shell: bash
      run: |
        cd /tmp
        git clone https://github.com/luna-ml/luna.git
        cd /tmp/luna
        git checkout ${{ inputs.version }}
        pip install -q -r requirements.txt
        pip install -e .

        if [ "${{ inputs.server }}" == "http://localhost:5000" ]; then
          # when server adddress is localhost, start local a server
          nohup ./run_dev_server.sh &

          # wait for server to start
          curl -s --retry 10 --retry-delay 2 --retry-connrefused localhost:5000/health
        fi
    - name: Sync
      shell: bash
      run: |
        echo "git fetch origin $GITHUB_BASE_REF"
        git fetch origin $GITHUB_BASE_REF

        if [ "${{ inputs.server }}" == "http://localhost:5000" ]; then        
          # sync with local server
          ORIG_COMMIT="origin/$GITHUB_BASE_REF"
          CURRENT_COMMIT="HEAD"

          # print task pod logs
          curl -s -L -O https://github.com/wercker/stern/releases/download/1.11.0/stern_linux_amd64
          chmod +x stern_linux_amd64
          ./stern_linux_amd64 -l task.luna-ml/type &

          echo "Evaluate locally"
          luna-ml --server ${{ inputs.server }} sync \
            --orig_commit "$ORIG_COMMIT" \
            --current_commit "$CURRENT_COMMIT" \
            --dry-run false \
            --eval true \
            --wait true .
        else
          # In case the action is running for push event
          set +e
          git show -s ${{ github.event.before }}
          if [ $? -ne 0 ]; then
            echo ""
            echo "+------------------------------------------------------------+"
            echo "| Maybe, the branch is deleted after the Pull request merge? |"
            echo "| Keep the branch until this action finishes.                |"
            echo "+------------------------------------------------------------+"
            echo ""
            exit -1
          fi
          set -e

          ORIG_COMMIT=${{ github.event.before }}
          CURRENT_COMMIT="HEAD"
          echo "Update remote server ${{ inputs.server }}"
          luna-ml --server ${{ inputs.server }} sync \
            --orig_commit "$ORIG_COMMIT" \
            --current_commit "$CURRENT_COMMIT" \
            --dry-run false \
            --eval true \
            --wait false .
        fi
      env:
        REPO_NAME: github.com/${{ github.repository }}
        LUNA_ACCESS_TOKEN: ${{ inputs.github-token }}
